volumes:
  mysql-data:
    name: ${PROJECT_NAME}-data

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: 8.0
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: "no"

  php:
    build:
      context: ./docker/php
      args:
        php_version: 8.2-apache
    container_name: ${PROJECT_NAME}-php-apache
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - mysql
      - postfix
    restart: "no"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: "no"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
 
  postfix:
    image: boky/postfix
    container_name: ${PROJECT_NAME}-postfix
    restart: "no"
    environment:
      ALLOWED_SENDER_DOMAINS: ${MAIL_DOMAIN}
      HOSTNAME: mail.${MAIL_DOMAIN}
    ports:
      - "25:25"