# =========================================================
# MySQL
# =========================================================
# Creacion de la imagen con el SGDB

# carga la imagen indicada en el fichero .env 
ARG mysql_version
FROM mysql:${mysql_version}
