# =========================================================
# MySQL
# =========================================================

# ./docker/mysql/Dockerfile
ARG MYSQL_VERSION=8.0
FROM mysql:${MYSQL_VERSION}

# Exponer puerto
EXPOSE 3306
